### ISSUE TITLE
Package does not install on Node.js 18

### ISSUE THREAD

**Issue by VitalyEmelyanov** [tacoss/testcafe-blink-diff#41]
The latest version of the [testcafe-blink-diff](https://github.com/tacoss/testcafe-blink-diff) (0.4.12) has added the following dependencies:
```
"native-image-diff": "^0.1.14",
"node-libpng": "^0.2.20",
```

This fails to install on Node v18:

```
npm ERR! code 1
npm ERR! path /usr/local/lib/node_modules/testcafe-blink-diff/node_modules/native-image-diff
npm ERR! command failed
npm ERR! command sh -c -- node scripts/install.js
npm ERR! Downloading native-image-diff prebuilt binary from "https://github.com/Prior99/native-image-diff/releases/download/0.1.14/native-image-diff-linux-x64-108.node".
npm ERR! /usr/local/lib/node_modules/testcafe-blink-diff/node_modules/native-image-diff/scripts/install.js:38
npm ERR!             throw new Error(`No supported native-image-diff ${packageVersion} build found for node ${process.version} on ${process.platform} (${process.arch}).`);
npm ERR!             ^
npm ERR!
npm ERR! Error: No supported native-image-diff 0.1.14 build found for node v18.8.0 on linux (x64).
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/testcafe-blink-diff/node_modules/native-image-diff/scripts/install.js:38:19)
npm ERR!     at Request.emit (node:events:513:28)
npm ERR!     at Request.onRequestResponse (/usr/local/lib/node_modules/testcafe-blink-diff/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:513:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:534:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
npm ERR!     at addChunk (node:internal/streams/readable:324:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:297:9)
npm ERR!
npm ERR! Node.js v18.8.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-08-29T05_30_24_728Z-debug-0.log
```

**Comment by pateketrueke** [comment]
Yeah, sadly it only supports up to v16 of node but I did not found faster alternatives... what's your recommendation on this cases? You would like to fork native-image-diff and build for v16+ so we can use your fork instead? Thank you!

**Comment by VitalyEmelyanov** [comment]
Why were these libraries added? What has changed compared to the previous versions that we now need them?

**Comment by pateketrueke** [comment]
The usage of blink-diff is no stable and it's archived 6 years ago, nothing else changed. I just researched a bit for alternatives, also pixelmatch can be used... but I did not tested it yet.

**Comment by VitalyEmelyanov** [comment]
native-image-diff looks also a bit outdated...

**Comment by pateketrueke** [comment]
Well, that'ts true too... then just wait until I replace it again, sorry.

**Comment by pateketrueke** [comment]
Or send a PR with your corrections, thank you.

**Comment by pateketrueke** [comment]
Update: pixelmatch works fine too... but it does not provides a way to fill areas on images, which is required for the blockout feature. 💭

**Comment by pateketrueke** [comment]
Update: pngjs works fine, but I did not grasp how to fill the blockOut areas... any help?

**Comment by pateketrueke** [comment]
Update: finally got it! 💣
